(() => {
  const $ = (s, root=document) => root.querySelector(s);
  const $$ = (s, root=document) => [...root.querySelectorAll(s)];
  const KEY_PRODUCTS='bloomora_products_v1', KEY_USERS='bloomora_customers_v1', KEY_SESSION='bloomora_session_v1';
  const defaults=[
    {id:'vase-1',name:'Blue Daisy Vase',price:3500,category:'floral blue gift',description:'Our signature cream-and-blue vase with hand-painted daisies.',image:'images/original-daisy-vase.png',tag:'BEST LOVED'},
    {id:'vase-2',name:'Sunset Bloom Vase',price:3200,category:'floral gift',description:'A warm floral look inspired by sunset colours.',image:'images/blue-daisy-vase.png',tag:'GIFT FAVOURITE'},
    {id:'vase-3',name:'Ocean Mist Vase',price:2900,category:'blue',description:'Calm blue tones for a soft, simple interior.',image:'images/blue-daisy-vase.png',tag:'CALM & COOL'},
    {id:'vase-4',name:'Meadow Days Vase',price:3300,category:'floral gift',description:'A garden-inspired design with fresh green details.',image:'images/original-daisy-vase.png',tag:'NATURE INSPIRED'}
  ];
  const get=(key,fallback)=>{try{const v=JSON.parse(localStorage.getItem(key));return v??fallback}catch{return fallback}};
  const set=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
  const money=n=>'LKR '+Number(n).toLocaleString('en-LK');
  const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function products(){let p=get(KEY_PRODUCTS,null);if(!p){p=defaults;set(KEY_PRODUCTS,p)}return p}
  function users(){return get(KEY_USERS,[])}
  function current(){return get(KEY_SESSION,null)}
  function orderLink(p){const msg=`Hi BLOO MORA! I'm interested in the ${p.name} (${money(p.price)}). Is it available?`;return 'https://wa.me/94740324570?text='+encodeURIComponent(msg)}
  function renderCustomer(){const grid=$('#customerProducts');if(!grid)return;const u=current();if(!u||u.role!=='customer'){location.href='auth.html';return}$('#customerName').textContent=(u.name||'flower lover').split(' ')[0];$('#customerGreeting').textContent=u.name||u.email;const q=($('#customerSearch')?.value||'').toLowerCase();const list=products().filter(p=>(p.name+' '+p.description+' '+p.category).toLowerCase().includes(q));$('#vaseCount').textContent=products().length;grid.innerHTML=list.length?list.map(p=>`<article class="portal-product"><div class="portal-product-image"><img src="${escape(p.image||'images/blue-daisy-vase.png')}" alt="${escape(p.name)}" onerror="this.src='images/blue-daisy-vase.png'"></div><div class="portal-product-info"><span class="mini-tag">${escape(p.category||'handmade')}</span><h3>${escape(p.name)}</h3><p>${escape(p.description||'Hand-painted with love.')}</p><strong>${money(p.price)}</strong><a class="button button-dark full" target="_blank" rel="noopener" href="${orderLink(p)}">Order on WhatsApp ↗</a></div></article>`).join(''):'<p class="empty-state">No vases match your search yet.</p>'}
  function renderAdmin(){if(!$('#adminProducts'))return;const list=products();$('#adminVaseCount').textContent=list.length;const host=$('#adminProducts');host.innerHTML=list.map(p=>`<article class="admin-product"><img src="${escape(p.image||'images/blue-daisy-vase.png')}" alt="" onerror="this.src='images/blue-daisy-vase.png'"><div class="admin-product-details"><b>${escape(p.name)}</b><small>${money(p.price)} · ${escape(p.category)}</small></div><button class="delete-btn" data-delete="${escape(p.id)}" aria-label="Delete ${escape(p.name)}">Delete</button></article>`).join('')||'<p class="muted">No products yet. Add your first vase.</p>';host.onclick=e=>{const b=e.target.closest('[data-delete]');if(!b)return;if(confirm('Remove this vase from the catalogue?')){set(KEY_PRODUCTS,products().filter(p=>p.id!==b.dataset.delete));renderAdmin()}};renderCustomers()}
  function renderCustomers(){if(!$('#customersTable'))return;const q=($('#adminCustomerSearch')?.value||'').toLowerCase();const list=users().filter(u=>(u.name+' '+u.email+' '+(u.phone||'')).toLowerCase().includes(q));$('#adminCustomerCount').textContent=users().length;$('#customersTable').innerHTML=list.map(u=>`<tr><td>${escape(u.name)}</td><td>${escape(u.email)}</td><td>${escape(u.phone||'—')}</td><td>${escape(u.joined||'—')}</td></tr>`).join('')||'<tr><td colspan="4">No registered customers found.</td></tr>'}
  // Auth page
  if($('#loginForm')){
    const tabs=$$('.tab'),login=$('#loginForm'),register=$('#registerForm');function switchTab(tab){tabs.forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));login.hidden=tab!=='login';register.hidden=tab!=='register'}tabs.forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));if(location.hash==='#register')switchTab('register');$('#switchLogin')?.addEventListener('click',e=>{e.preventDefault();switchTab('login')});
    login.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(login),email=String(data.get('email')).trim().toLowerCase(),password=String(data.get('password'));const u=users().find(x=>x.email===email&&x.password===password);if(!u){$('#loginMessage').textContent='We could not find that account. Check your details or create an account.';return}set(KEY_SESSION,{role:'customer',name:u.name,email:u.email});location.href='customer.html'});
    register.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(register),name=String(data.get('name')).trim(),email=String(data.get('email')).trim().toLowerCase(),password=String(data.get('password'));const all=users();if(all.some(u=>u.email===email)){$('#registerMessage').textContent='An account with this email already exists. Please log in.';return}const user={id:'c-'+Date.now(),name,email,password,phone:String(data.get('phone')||'').trim(),joined:new Date().toLocaleDateString()};all.push(user);set(KEY_USERS,all);set(KEY_SESSION,{role:'customer',name,email});location.href='customer.html'});
  }
  if($('#customerProducts')){renderCustomer();$('#customerSearch').addEventListener('input',renderCustomer);$('#logoutBtn').addEventListener('click',()=>{localStorage.removeItem(KEY_SESSION);location.href='index.html'})}
  if($('#adminLoginForm')){
    const loginPanel=$('#adminLoginPanel'),panel=$('#adminPanel');function openAdmin(){loginPanel.hidden=true;panel.hidden=false;renderAdmin()};if(sessionStorage.getItem('bloomora_admin_demo')==='yes')openAdmin();
    $('#adminLoginForm').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget);if(String(d.get('email')).trim().toLowerCase()==='admin@bloomora.lk'&&String(d.get('password'))==='BloomAdmin123'){sessionStorage.setItem('bloomora_admin_demo','yes');openAdmin()}else $('#adminLoginMessage').textContent='Incorrect demo admin details. Please try again.'});
    $('#adminLogout').addEventListener('click',()=>{sessionStorage.removeItem('bloomora_admin_demo');location.reload()});
    $('#addVaseForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,d=new FormData(form);let image=String(d.get('image')||'').trim()||'images/blue-daisy-vase.png';const file=form.elements.photo.files[0];if(file){if(file.size>1500000){$('#addVaseMessage').textContent='Please choose an image smaller than 1.5 MB.';return}image=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}const p=products();p.unshift({id:'vase-'+Date.now(),name:String(d.get('name')).trim(),price:Number(d.get('price')),category:String(d.get('category')),description:String(d.get('description')||'Hand-painted with love.').trim(),image,tag:'NEW'});try{set(KEY_PRODUCTS,p)}catch{$('#addVaseMessage').textContent='Browser storage is full. Try a smaller image or use an image URL.';return}form.reset();$('#addVaseMessage').textContent='Vase added to the catalogue!';renderAdmin()});$('#adminCustomerSearch').addEventListener('input',renderCustomers);
  }
  // Homepage account buttons and products added from admin (same browser demo storage).
  const homeGrid=$('#productGrid');if(homeGrid){const initialMarkup=homeGrid.innerHTML;const saved=get(KEY_PRODUCTS,null);if(saved&&saved.length){homeGrid.innerHTML=saved.map(p=>`<article class="product-card" data-category="${escape(p.category||'other')}" data-name="${escape(p.name.toLowerCase())}"><div class="product-image"><span class="product-tag">${escape(p.tag||'HANDMADE')}</span><img src="${escape(p.image||'images/blue-daisy-vase.png')}" alt="${escape(p.name)}" onerror="this.src='images/blue-daisy-vase.png'"><button class="quick-order" data-product="${escape(p.name)}" data-price="${Number(p.price)}">Quick order ↗</button></div><div class="product-info"><div><h3>${escape(p.name)}</h3><p>${escape(p.description||'Hand-painted with love.')}</p></div><strong>${money(p.price)}</strong></div></article>`).join('')}const filterButtons=$$('.filter');let activeFilter='all';function updateHome(){const q=($('#productSearch')?.value||'').trim().toLowerCase();let shown=0;$$('.product-card',homeGrid).forEach(card=>{const cats=card.dataset.category.split(' ');const ok=(activeFilter==='all'||cats.includes(activeFilter))&&(card.dataset.name.includes(q)||card.textContent.toLowerCase().includes(q));card.hidden=!ok;if(ok)shown++});const old=$('.empty-state',homeGrid);if(old)old.remove();if(!shown)homeGrid.insertAdjacentHTML('beforeend','<p class="empty-state">No vases found. Try another search.</p>')}filterButtons.forEach(b=>b.addEventListener('click',()=>{filterButtons.forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;updateHome()}));$('#productSearch')?.addEventListener('input',updateHome);homeGrid.addEventListener('click',e=>{const b=e.target.closest('.quick-order');if(b){const p=products().find(x=>x.name===b.dataset.product)||{name:b.dataset.product,price:b.dataset.price};window.open(orderLink(p),'_blank','noopener')}});const toggle=$('#menuToggle'),nav=$('#navLinks');toggle?.addEventListener('click',()=>nav.classList.toggle('open'));nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));$('#year')&&($('#year').textContent=new Date().getFullYear());}
})();
